/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.galley.grub;

public class App {
    public static void main(String[] args) {
        /**
         * Crea un diccionario con los precios
         * de los extras.
         *  
         *  Los precios de los extras son estos:
         *  - cheese +0.25
         *  - sauce +0.50
         *  - medium +0.25
         *  - large +0.50
         * 
         * Lee los precios de los items en la imagen 
         * del menu proporcionada.
         */

         RetailPrice.init_prices();
    }
}
